server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  http:
    encoding:
      charset: UTF-8
#      enabled: true
#      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#多数据源相关配置
druid:
  type: com.alibaba.druid.pool.DruidDataSource
  mysqlmaster:
    url: jdbc:mysql://192.168.56.20:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    dirver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19950404ljh
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
  mysqlslaveone:
    url: jdbc:mysql://192.168.56.21:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    dirver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19950404ljh
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
  postgres:
    dirver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.90:5432/sign_public_test
    username: postgres
    password: postgres
pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
  helper-dialect: PostgreSQL
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mojita.integration.core.entity
  configuration:
    map-underscore-to-camel-case: true
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: true
mapper:
  mappers: com.mojita.integration.core.common.basedao.BaseMapper
  not-empty: false
logging:
  level:
    com.mojita.integration.core.dao: debug
